import { useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, ArrowRight, Check, ChevronDown, CircleHelp, Filter, MapPin, Pencil, Plus, Search, Sparkles, Trash2, WalletCards, X } from 'lucide-react'
import './styles.css'

const API = 'http://localhost:8000/api'
const categories = ['Food & drinks', 'Stay', 'Transport', 'Activities', 'Other']
const people = [
  { name: 'Aarav', initials: 'AR', color: '#f4a261' }, { name: 'Meera', initials: 'ME', color: '#5b8e7d' },
  { name: 'Kabir', initials: 'KB', color: '#e76f51' }, { name: 'Priya', initials: 'PR', color: '#8d6e9f' },
  { name: 'Rohan', initials: 'RO', color: '#3a86ff' }, { name: 'Nisha', initials: 'NI', color: '#e9c46a' },
]
const fallback = { members: people, total: 0, expenses: [], balances: [], settlements: [] }

function money(value) { return `₹${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` }
function avatar(name, small = false) { const person = people.find(item => item.name === name) || people[0]; return <span className={`avatar ${small ? 'small' : ''}`} style={{ backgroundColor: person.color }}>{person.initials}</span> }

export default function App() {
  const [data, setData] = useState(fallback); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All expenses')
  const [activeView, setActiveView] = useState('Expenses'); const [editor, setEditor] = useState(null); const [paid, setPaid] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const refresh = () => fetch(`${API}/overview`).then(response => { if (!response.ok) throw new Error('Could not load trip'); return response.json() }).then(setData)
  useEffect(() => { refresh().catch(() => setError('Showing a blank trip. Start the API to load and sync expenses.')).finally(() => setLoading(false)) }, [])
  const filtered = useMemo(() => data.expenses.filter(expense => `${expense.title} ${expense.category} ${expense.paid_by} ${expense.note}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All expenses' || expense.category === filter)), [data.expenses, query, filter])
  const average = data.members.length ? data.total / data.members.length : 0; const topSpender = [...data.balances].sort((a, b) => b.paid - a.paid)[0]
  async function submitExpense(payload) { setError(''); try { const response = await fetch(`${API}/expenses${editor?.id ? `/${editor.id}` : ''}`, { method: editor?.id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('Could not save expense'); await refresh() } catch { setError('Could not save this expense. Check that the API is running.') } finally { setEditor(null) } }
  async function removeExpense(expense) { if (!window.confirm(`Remove ${expense.title}?`)) return; try { const response = await fetch(`${API}/expenses/${expense.id}`, { method: 'DELETE' }); if (!response.ok) throw new Error(); await refresh() } catch { setError('Could not remove this expense. Check that the API is running.') } }

  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><WalletCards size={19} /></span><span>splitwisely</span></div><div className="trip-picker"><MapPin size={15} /> <span>Goa, 12–16 Feb</span><ChevronDown size={15} /></div><button className="help-button" title="How it works" onClick={() => setError('Add what someone paid, choose only the people who benefited, then settle up.') }><CircleHelp size={19} /></button><div className="profile">AK</div></header><main>
    <section className="hero"><div><div className="eyebrow"><Sparkles size={14} /> TRIP DASHBOARD</div><h1>Goa, we’re even.</h1><p>Six friends. Four days. One clean slate.</p></div><button className="primary-button" onClick={() => setEditor({})}><Plus size={18} /> Add expense</button></section>
    {error && <div className="notice"><span>{error}</span><button onClick={() => setError('')}><X size={15} /></button></div>}<nav className="view-tabs"><button className={activeView === 'Expenses' ? 'active' : ''} onClick={() => setActiveView('Expenses')}>Expenses <span>{data.expenses.length}</span></button><button className={activeView === 'Settle up' ? 'active' : ''} onClick={() => setActiveView('Settle up')}>Settle up <span className="tab-badge">{data.settlements.length - paid.length}</span></button></nav>
    {activeView === 'Expenses' ? <><section className="stats-grid"><div className="stat-card total-card"><span className="stat-label">TOTAL SPENT</span><strong>{money(data.total)}</strong><span className="stat-foot">Across {data.expenses.length} expenses</span></div><div className="stat-card"><span className="stat-label">EACH PERSON</span><strong>{money(average)}</strong><span className="stat-foot">The perfectly fair share</span></div><div className="stat-card"><span className="stat-label">BIGGEST TAB</span><strong>{money(topSpender?.paid || 0)}</strong><span className="stat-foot">{topSpender?.name || 'Nobody'} fronted the most</span></div></section><div className="content-grid"><section className="expenses-panel"><div className="section-heading"><div><h2>What happened</h2><p>Every chai, cab and questionable late-night decision.</p></div><button className="icon-button" title="Filter expenses"><Filter size={18} /></button></div><div className="toolbar"><div className="search"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search expenses" /></div><select value={filter} onChange={event => setFilter(event.target.value)}><option>All expenses</option>{categories.map(category => <option key={category}>{category}</option>)}</select></div><div className="expense-list">{loading ? <div className="empty">Loading the trip...</div> : filtered.map(expense => <ExpenseRow key={expense.id} expense={expense} onEdit={() => setEditor(expense)} onDelete={() => removeExpense(expense)} />)}{!loading && !filtered.length && <div className="empty">No expenses match that search.</div>}</div></section><aside className="side-panel"><div className="section-heading"><div><h2>At a glance</h2><p>Who’s up, who’s down.</p></div></div><div className="people-list">{data.balances.map(balance => <div className="person-row" key={balance.name}>{avatar(balance.name, true)}<div className="person-info"><strong>{balance.name}</strong><span>{money(balance.paid)} paid · {money(balance.owed)} share</span></div><div className={balance.net >= 0 ? 'positive' : 'negative'}>{balance.net >= 0 ? '+' : '-'}{money(Math.abs(balance.net))}</div></div>)}</div><div className="tip"><Sparkles size={16} /><span><b>Fair doesn't mean equal.</b> Choose participants per expense. Priya stays out of the beer run, and only divers split scuba.</span></div></aside></div></> : <SettlementView data={data} paid={paid} setPaid={setPaid} />}</main><footer><span>splitwisely</span><span>Made for the group chat that never sleeps.</span></footer>{editor && <ExpenseModal expense={editor} members={data.members} onClose={() => setEditor(null)} onSave={submitExpense} />}</div>
}

function ExpenseRow({ expense, onEdit, onDelete }) { return <article className="expense-row"><div className={`category-icon ${expense.category.toLowerCase().replaceAll(' ', '-')}`}>{expense.category === 'Stay' ? '⌂' : expense.category === 'Transport' ? '↗' : expense.category === 'Activities' ? '✦' : '◌'}</div><div className="expense-main"><div className="expense-title"><strong>{expense.title}</strong><span className="day-tag">{expense.day}</span></div><span className="expense-meta">{avatar(expense.paid_by, true)} <span>{expense.paid_by} paid</span><i>•</i><span>{expense.split_between.length} people</span></span>{expense.note && <span className="expense-note">{expense.note}</span>}</div><strong className="expense-amount">{money(expense.amount)}</strong><div className="row-actions"><button title="Edit expense" onClick={onEdit}><Pencil size={14} /></button><button title="Delete expense" onClick={onDelete}><Trash2 size={14} /></button></div></article> }

function ExpenseModal({ expense, members, onClose, onSave }) { const [participants, setParticipants] = useState(expense.split_between || members.map(member => member.name)); const toggle = name => setParticipants(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]); return <div className="modal-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><form className="modal" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ title: form.get('title'), category: form.get('category'), amount: Number(form.get('amount')), paid_by: form.get('paid_by'), split_between: participants, day: form.get('day'), note: form.get('note') || '' }) }}><div className="modal-header"><div><span className="eyebrow">{expense.id ? 'EDIT EXPENSE' : 'NEW EXPENSE'}</span><h2>What did someone pay for?</h2></div><button type="button" className="close-button" onClick={onClose}><X size={19} /></button></div><label>Expense name<input name="title" defaultValue={expense.title} placeholder="e.g. Beach shack lunch" required /></label><div className="form-row"><label>Amount<input name="amount" type="number" min="0.01" step="0.01" defaultValue={expense.amount} placeholder="0.00" required /></label><label>Day<select name="day" defaultValue={expense.day || 'Day 1'}>{[1, 2, 3, 4].map(day => <option key={day}>Day {day}</option>)}</select></label></div><div className="form-row"><label>Paid by<select name="paid_by" defaultValue={expense.paid_by || members[0].name}>{members.map(member => <option key={member.name}>{member.name}</option>)}</select></label><label>Category<select name="category" defaultValue={expense.category || 'Food & drinks'}>{categories.map(category => <option key={category}>{category}</option>)}</select></label></div><fieldset><legend>Split between <span>{participants.length} selected</span></legend><div className="participant-grid">{members.map(member => <button type="button" className={participants.includes(member.name) ? 'participant selected' : 'participant'} key={member.name} onClick={() => toggle(member.name)}>{avatar(member.name, true)}<span>{member.name}</span>{participants.includes(member.name) && <Check size={14} />}</button>)}</div>{!participants.length && <small className="validation">Choose at least one person.</small>}</fieldset><label>Note <span className="optional">optional</span><input name="note" defaultValue={expense.note} placeholder="A little context helps later" /></label><button className="primary-button full" type="submit" disabled={!participants.length}><Check size={18} /> {expense.id ? 'Save changes' : 'Add to trip'}</button></form></div> }

function SettlementView({ data, paid, setPaid }) { const outstanding = data.settlements.filter((_, index) => !paid.includes(index)); return <section className="settle-page"><div className="settle-intro"><div className="eyebrow"><Check size={14} /> READY TO CLOSE OUT</div><h2>{outstanding.length ? `${outstanding.length} payments and` : 'Everyone is'}<br /><em>{outstanding.length ? 'you’re square.' : 'all square.'}</em></h2><p>{outstanding.length ? 'We’ve untangled the tabs into the fewest possible transfers.' : 'The trip is settled. Beautifully uneventful.'}</p></div><div className="settlement-list">{data.settlements.map((item, index) => <div className={paid.includes(index) ? 'settlement-row settled' : 'settlement-row'} key={`${item.from}-${item.to}`}><span className="settle-number">0{index + 1}</span><div className="transfer-person">{avatar(item.from)}<strong>{item.from}</strong></div><ArrowRight className="arrow-right" size={18} /><div className="transfer-person">{avatar(item.to)}<strong>{item.to}</strong></div><strong className="transfer-amount">{money(item.amount)}</strong><button className="mark-button" title={paid.includes(index) ? 'Mark as unpaid' : 'Mark as paid'} onClick={() => setPaid(current => current.includes(index) ? current.filter(itemIndex => itemIndex !== index) : [...current, index])}><Check size={17} /></button></div>)}</div><div className="settle-note"><ArrowDownLeft size={17} /><span>Each person’s fair share is <b>{money(data.total / data.members.length)}</b>. Transfers are calculated to minimize the number of payments.</span></div></section> }
