# Generated by Django 6.1.1 on 2026-09-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(default="Goa", max_length=120)),
                ("date_label", models.CharField(default="12–16 Feb", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("color", models.CharField(default="#5b8e7d", max_length=7)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("trip", "name")},
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Stay", "Stay"),
                            ("Food & drinks", "Food & drinks"),
                            ("Transport", "Transport"),
                            ("Activities", "Activities"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Day 1", "Day 1"),
                            ("Day 2", "Day 2"),
                            ("Day 3", "Day 3"),
                            ("Day 4", "Day 4"),
                        ],
                        default="Day 1",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_expenses",
                        to="trip.member",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="shared_expenses", to="trip.member"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
